project:
  type: website
  output-dir: docs

website:
  title: "Raihan's Website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: My Projects
      - href: Data_Visualisations.qmd
        text: Data Visualisations
      - href: reflections.qmd
        text: Reflections
      
        

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



